FROM learningbydoingdocker/codalab-competition-docker:latest

## Install pytorch-cpu inside it
RUN pip3 install torch==1.9.0+cpu torchvision==0.10.0+cpu \ 
    torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html